{
 "title": "Patient Monitor - Dev1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Clock",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Oxygen Saturation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as oxygen_saturation,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'oxygen_saturation' AND \n  vital_value <= 100 AND\n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Oxygen Saturation (%)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as oxygen_saturation,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'oxygen_saturation' AND \n  vital_value <= 100 AND\n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Device 1 - PM6100",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  rented_to_name\nFROM device_rentals\nWHERE\n  device_id = 'rpm-dev-1' AND \n  returned_at IS null \n  \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Heart Rate ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as oxygen_saturation,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'heart_rate' AND \n  vital_value <= 200 AND\n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Heart Rate (bpm)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as oxygen_saturation,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'heart_rate' AND \n  vital_value <= 200 AND\n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "AVPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as consciousness\nFROM rpm_data\nWHERE\n  vital_type = 'consciousness' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Score",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as oxygen_saturation,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'temperature' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as oxygen_saturation,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'temperature' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Respiratory Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as oxygen_saturation,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'respiratory_rate' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Respiratory Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as oxygen_saturation,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'respiratory_rate' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Blood Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as Systolic\nFROM rpm_data\nWHERE\n  vital_type = 'nbp_systolic' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as Diastolic\nFROM rpm_data\nWHERE\n  vital_type = 'nbp_diastolic' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Blood Pressure",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as systolic\nFROM rpm_data\nWHERE\n  vital_type = 'nbp_systolic' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as diastolic\nFROM rpm_data\nWHERE\n  vital_type = 'nbp_diastolic' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  }
 ]
}