{
 "title": "Virtual-Ward-1",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Clock",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 5, "y": 0 },
   "options": { "content": "##### Patients\n\n" },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "options": {
    "content": "### MEW-Score\nLast Registered \n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "options": {
    "content": "### MEW-Score\n\nLast Updated at: \n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Device 1 - PM6100",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  rented_to_name,concat('Patient id: ',rented_to_uid)\nFROM device_rentals\nWHERE\n  device_id = 'rpm-dev-1' AND \n  returned_at IS null \n  \nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Simulated 1 - PM6100",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  rented_to_name,concat('Patient id: ',rented_to_uid)\nFROM device_rentals\nWHERE\n  device_id = 'rpm-pbi-dev-1' AND \n  returned_at IS null \n  \nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-pbi-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-pbi-dev-1' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Simulated Device 2 - PM6100",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  rented_to_name, concat('Patient id: ',rented_to_uid)\nFROM device_rentals\nWHERE\n  device_id = 'rpm-pbi-dev-2' AND \n  returned_at IS null \n  \nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-pbi-dev-2' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-pbi-dev-2' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Simulated Device 3 - PM6100",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  rented_to_name,concat('Patient id: ',rented_to_uid)\nFROM device_rentals\nWHERE\n  device_id = 'rpm-pbi-dev-3' AND \n  returned_at IS null \n  \nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-pbi-dev-3' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-pbi-dev-3' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Simulated Device 4 - PM6100",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  rented_to_name, concat('Patient id: ',rented_to_uid)\nFROM device_rentals\nWHERE\n  device_id = 'rpm-pbi-dev-4' AND \n  returned_at IS null \n  \nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-pbi-dev-4' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  vital_value as mews,\n  rented_to_name as patient_name\nFROM rpm_data\nWHERE\n  vital_type = 'mew_score' AND \n  device_id = 'rpm-pbi-dev-4' AND\n  $__timeFilter(recorded_at)\nORDER BY 1,2"
    }
   ]
  }
 ]
}