{
 "title": "Patient Monitor - Dev2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Clock",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Oxygen Saturation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  device_id AS metric,\n  oxygen_saturation\nFROM rpmc\nWHERE\n  $__timeFilter(recorded_at) AND\n  device_id = 'rpm-pbi-dev-2'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Oxygen Saturation (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  device_id AS metric,\n  oxygen_saturation\nFROM rpmc\nWHERE\n  $__timeFilter(recorded_at) AND\n  device_id = 'rpm-pbi-dev-2'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Device 2 - PM6100",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  rented_to\nFROM devices\nWHERE\n  id = 'rpm-pbi-dev-2'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Heart Rate ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  device_id AS metric,\n  heart_rate\nFROM rpmc\nWHERE\n  $__timeFilter(recorded_at) AND\n  device_id = 'rpm-pbi-dev-2'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Heart Rate (bpm)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  device_id AS metric,\n  heart_rate\nFROM rpmc\nWHERE\n  $__timeFilter(recorded_at) AND\n  device_id = 'rpm-pbi-dev-2'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  device_id AS metric,\n  temperature\nFROM rpmc\nWHERE\n  $__timeFilter(recorded_at) AND\n  device_id = 'rpm-pbi-dev-2'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  recorded_at AS \"time\",\n  device_id AS metric,\n  temperature\nFROM rpmc\nWHERE\n  $__timeFilter(recorded_at) AND\n  device_id = 'rpm-pbi-dev-2'\nORDER BY 1,2"
    }
   ]
  }
 ]
}